### ISSUE TITLE
Update to elm 0.19.1

### ISSUE THREAD

**Issue by mpizenberg** [exercism/elm#278]
Meta-issue regarding the update to elm 0.19.1 All code modification should happen in branch elm-0.19.1

- [x] (1) Update config/exercise_readme.go.tmpl. Use the ruby track as a reference: https://github.com/exercism/ruby/blob/master/config/exercise_readme.go.tmpl. CF issue https://github.com/exercism/elm/issues/225. Done in 66a3a1b
- [x] (2) Update elm/docs. Done in PR #282
    - [x] about
    - [x] installation, cf https://github.com/exercism/elm/issues/238
    - [x] learning
    - [x] resources
    - [x] snippet
    - [x] tests, cf https://github.com/exercism/elm/issues/238
- [x] (3) Check exercise names, cf https://github.com/exercism/elm/issues/253
- [x] (4) Update source code directory of every exercise to be `"src"` instead of `"."` in `elm.json` and move files accordingly. done in defe475 
- [x] (5) Update npm dependencies (cf https://github.com/exercism/elm/pull/274) and Travis CI to latest LTS. done in 839899d and b80ddcc
- [x] (6) Update readme instructions (cf https://github.com/exercism/elm/issues/193). Done in PR #281

**Comment by mpizenberg** [comment]
If you want to help by starting working on something, please post a message here to avoid duplicate work.

**Comment by mpizenberg** [comment]
I'll start with (4) and (5) to have things compile

**Comment by mpizenberg** [comment]
ping @leojpod

**Comment by mpizenberg** [comment]
I'm going to update readme instructions (6).

**Comment by mpizenberg** [comment]
Updating docs (2) in PR #282

**Comment by mpizenberg** [comment]
Merged
