### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/elm#326]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/elm/issues/317)
- [x] [Add key features](https://github.com/exercism/elm/issues/318)
- [x] [Add tags](https://github.com/exercism/elm/issues/319)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/elm/issues/320)
- [x] [Update status of track](https://github.com/exercism/elm/issues/324)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/elm/issues/325)
- [x] [Pass linting checks](https://github.com/exercism/elm/issues/321)
- [x] [Build Test Runner](https://github.com/exercism/elm/issues/322)
- [x] [Build Analyzer and Representer](https://github.com/exercism/elm/issues/323) (optional)
- [x] [Add blurb to Concept Exercises](https://github.com/exercism/elm/issues/336)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7

**Comment by mpizenberg** [comment]
V3 has launched :)
Closing this in favor of each issue left to do to improve the situation. I attributed those with high priority tag
